### ISSUE TITLE
Support GHC-8.8.4

### ISSUE THREAD

**Issue by juev** [kowainik/summoner#512] opened 2020-10-16 20:13 UTC
Hi!

I used ghcup for install GHC and other tools. In this time ghcup list produced:
```bash
$ ghcup list
[ Warn  ] New HLS version available: 0.5.1. To upgrade, run 'ghcup install hls 0.5.1'
   Tool  Version        Tags                      Notes
✗  ghc   7.10.3         base-4.8.2.0
✗  ghc   8.0.2          base-4.9.1.0
✗  ghc   8.2.2          base-4.10.1.0
✗  ghc   8.4.1          base-4.11.0.0
✗  ghc   8.4.2          base-4.11.1.0
✗  ghc   8.4.3          base-4.11.1.0
✗  ghc   8.4.4          base-4.11.1.0
✗  ghc   8.6.1          base-4.12.0.0
✗  ghc   8.6.2          base-4.12.0.0
✗  ghc   8.6.3          base-4.12.0.0
✗  ghc   8.6.4          base-4.12.0.0             hls-powered
✗  ghc   8.6.5          base-4.12.0.0             hls-powered
✗  ghc   8.8.1          base-4.13.0.0
✗  ghc   8.8.2          base-4.13.0.0             hls-powered
✗  ghc   8.8.3          base-4.13.0.0             hls-powered
✓  ghc   8.8.4          recommended,base-4.13.0.0 hls-powered
✗  ghc   8.10.1         base-4.14.0.0             hls-powered
✔✔ ghc   8.10.2         latest,base-4.14.1.0      hls-powered
✗  ghc   9.0.0.20200925 prerelease,base-4.15.0.0
✗  cabal 2.4.1.0
✗  cabal 3.0.0.0
✔✔ cabal 3.2.0.0        latest,recommended
✗  cabal 3.4.0.0-rc4    prerelease
✓  hls   0.4.0                                    stray
✔✔ hls   0.5.0                                    stray
✗  hls   0.5.1          latest,recommended
✔✔ ghcup 0.1.11         latest,recommended
```

GHC version is recommended 8.8.4, but summoner will create only with these versions:
```bash
The project will be created with GHC-8.8.3
Additionally you can specify versions of GHC to test with (space-separated):
  Supported by 'summoner' GHCs: 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.3
```

We need support latest recommended version too.

**Comment by vrom911** [comment] 2020-10-17 10:14
Thanks for the report! This is a duplicate of https://github.com/kowainik/summoner/issues/491 which was already implemented in the master 🙂

**Closed by vrom911** 2020-10-17 10:14 UTC
Labels: duplicate

**Comment by juev** [comment] 2020-10-17 15:54
I found what happened!

I installed summoner from homebrew. In this time we have version 2.0.0.0 on homebrew, but from repository we have v2.0.1.1 version.

We need to update homebrew repository too. 

@vrom911

**Comment by vrom911** [comment] 2020-10-18 11:29
Oh, yeah, you are right!

The GHC-8.8.4 support is not in any official release yet, so we would add homebrew update in the coming release as well 🙂  Great catch, @juev ! 👍🏼
