### ISSUE TITLE
Support Stack templates

### ISSUE THREAD

**Issue by m-renaud** [kowainik/summoner#271] opened 2018-12-01 18:25 UTC
It would be awesome if Summoner was able to use Stack templates to initialize a project. I've looked at their structure a bit and there doesn't seem to be anything Stack specific about most of them, they appear to just use [Mustache](https://mustache.github.io/).

Also, according to [this issue](https://github.com/commercialhaskell/stack/issues/2681) there's plans to revamp the system, it seems like a good opportunity to make them available to a wider range of users.

**Comment by vrom911** [comment] 2018-12-02 05:13
@m-renaud, what would be the task of Summoner then? What Summoner could bring to Stack templates that is not already covered by Stack?
The purpose of the Stack templates is very different from what we are doing, and they can't be interactive, which cuts all the features we have in Summoner now, as we are building the tool on top of this freedom of the choice. I guess you'd better use Stack itself for this, as Summoner has different features and design. If we're using the stack templates we can't make any assumptions on what is the structure of the project like, what is already covered by the template and so on, so we can't push any of the features we are using in there, cause it makes no sense to rewrite what user requested by templates. And building even more complicated template engine on top of the stack templates sounds frightening.
I think that `summoner`'s task is not to just reuse the other tools, but with stack templates we are losing the ability to control all we are doing, so to have the wrapper over stack templates is pointless in my opinion.
We were starting as the tool over the stack template. We literally created `template.hsfiles` depending on the user input and created the project with `stack new project_name template.hsfiles` command, but we gave up on this approach as it was restricting us a lot. Also, it required internet connection and was quite slow. So, coming back to what we refused pulls us back not forward.

**Comment by m-renaud** [comment] 2018-12-02 06:53
@vrom911 thanks for the history about creating template.hsfiles, that's an interesting data point.

> what would be the task of Summoner then?

I view Summoner as the go-to tool for initializing a new project. There are various types of initialization that I see a user wanting: sometimes I just want a simple executable to play around with, sometimes I want to utilize the Summoner interactive initialization workflow, and other times I want to start a project to build a new REST API using Servant (for example purposes). The current story requires using 3 different "init" workflows depending on which one of those I want.

If I want a simple executable I run `cabal init -n --is-executable`. If I want a better interactive init I run `summon new myNewProject`. If I want to start a new Servant project I run `stack new myNewProject servant`. Another inconvenience is that I don't use Stack as my build tool, so now I need to install Stack just so that I can initialize the project.

I think Summoner can do better, if it could handle these then I would just need something like: `summon new myNewProject -n --exe`, `summon new myNewProject`, or `summon new myNewProject --template=servant` (subject to better names, etc.)

Maybe this isn't the goal of Summoner, and that's completely fine, just thought I would ask :)

**Comment by vrom911** [comment] 2018-12-02 08:01
@m-renaud , I see. It's totally great to hear the ideas, thanks for bringing up that!

FYI, Summoner can also use the command-line arguments to handle cases non-interactively (this options won't be asked during the process when specified). For example, you can:

```
summon new project with --exec without --github --library --benchmark --test
```
So it's a bit covers the first case you're talking about.

Regarding stack templates. It doesn't sound good to just rewrite Stack inside Summoner, but if we just reuse Stack here you still will need Stack to be installed on your machine + it's opinionated and we don't want Summoner to become an opinionated tool and it took a lot of effort to not be opinionated regarding the build tool that users should use, we want it to be used by all users. Also, the stack template is uncontrollable, we are using different kind of configurations (via TOML file, or CLI arguments) and none of them is supported by stack template, so Summoner would be helpless with dealing for example with custom written `.cabal` file inside of the `temlate.hsfiles` file.

But if you have an idea of how Summoner can do something similar, but keeping the features of the tool, I would be happy to hear that. For the moment I don't see how the template stuff is applied to the Summoner itself, only to Stack.

**Comment by m-renaud** [comment] 2018-12-02 20:09
Thanks @vrom911 and @ChShersh for the thoughtful reply,

> Summoner can also use the command-line arguments to handle cases non-interactively...

Yes, but that's a lot to remember and type to get a simple project ;P Having some option which creates a project with reasonable defaults non-interactively (but without having to pass a bunch of options) would be a nice to have. Something like a `summon --simple` option which creates a new project with "reasonable defaults" would work, although I imagine that set of "reasonable defaults" may be contentious.

> but if we just reuse Stack here...

Agreed that reusing Stack wouldn't be the right way forward.

>  It doesn't sound good to just rewrite Stack inside Summoner

I'm pretty sure this can be accomplished without the need to rewrite most of Stack, but I do admit the Stack codebase has a lot of nice HTTP request helper functions. AFAIK Stack templates are just Mustache templates, so code would need to be written to download a template, parse it to determine template arguments needed, and then render it. This is a lot of effort though as you mention.

I wonder if the Stack folks would be open to the idea of splitting out the template download/parse/application code into its own library that could be used by both Stack and Summoner. I can reach out and see what they think of the idea.

>  If we're going to implement project scaffolding from template, it looks better to come up with our own system for templates

I'm -1 on this, this would require template authors to then publish templates in two formats which I doubt many would do. This would result in different sets of available templates depending on which tool you're using which is not a great user experience.

**Comment by vrom911** [comment] 2018-12-03 04:01
> Yes, but that's a lot to remember and type to get a simple project ;P 

Well, this is indeed a problem that one should learn some new command to be able to use the tool.. But I don't see how to avoid it, unless not using the tool at all (as you showed in the example of what you're doing to create different kind of projects). It's pretty sad, but also I don't think that one letter is something too hard to learn. This command is identical to what I wrote above:

```
summon new project with -e without -gltb
```

>  although I imagine that set of "reasonable defaults" may be contentious.

Yes, it's not clear what is the right defaults 🤔 After this discussion I think that we can add some option which won't ask any questions interactively and use the default config that is already in there (it might be the config file, or command-line arguments). Thanks for bringing this up! But it's one more option to remember, not sure if it's helpful for you or not. Please feel free to comment in the corresponding issue, if you think that it could be useful in any way for you: #114. I see you would like Summoner to contain features and designs of other tools, so I don't know if the introduction of the new commands if satisfactorily solution to convince you to use Summoner for these purposes.

> I can reach out and see what they think of the idea.

Thanks for this! We can discuss the work in this direction after we receive some answers from the guys. Very kind of you to help with solving these non-trivial issues ❤️

**Comment by m-renaud** [comment] 2018-12-03 04:19
> Well, this is indeed a problem that one should learn some new command to be able to use the tool..

Haha, of course ;)

My motivation is providing the simplest dev-ex as possible for beginners (which has historically been an issue for Haskell tooling), without introducing friction for those that want all the features. Asking a beginner to run `summon new project with -e without -gltb` will probably lead to questions about "what does this `-gltb` mean?" and adds a few more distractions then necessary. I agree that you can accomplish the "simple project initialization" with existing commands, but the UI leaves a bit to be desired.

I recently added a `--simple` option to `cabal init` which will give you (when its all done) a project scaffolding with "reasonable defaults" (src/Lib.hs, app/Main.hs, new cabal spec version, common stanzas, a test and benchmark suite, etc), just by running `cabal init --simple`.

> I think that we can add some option which won't ask any questions interactively and use the default config that is already in there

:+1:

> I see you would like Summoner to contain features and designs of other tools

I'm more just thinking out loud about features that others may find useful :)

> without using Stack it's not possible to create the complete Stack project as the stack.yaml file won't be created because it's not the part of the template file

Hmm, good point, yeah this will definitely require a decent amount of design work. I'll report back with what I find out.

Anyways, thanks for all the feedback on the idea so far! :)

**Comment by ChShersh** [comment] 2018-12-03 04:51
> Please feel free to comment in the corresponding issue, if you think that it could be useful in any way for you: #114

@vrom911 Thanks for writing the plan for this issue!

> I'm -1 on this, this would require template authors to then publish templates in two formats which I doubt many would do.

One of my main concerns about reusing Stack templates is that they don't really provide much configuration. Only simple stuff like email or author name. This makes this _templating mode_ inconsistent with other features of Summoner. Even if we figure out some way to make parts of the existing Stack template engine configurable (like `{{ benchmark }}` Mustache variable), this still will result into inconsistent set of templates: some variables are recognized by Stack and some of them are only by Summoner. Also, as @vrom911 mentioned, there're some unresolved problems with using existing Stack templates, the design space is too big and the amount of work is huge.

Though, I really appreciate the discussion! I also want Summoner to become more popular, to contain convenient and useful user interface for many people! But some problems are really difficult 😞

**Comment by nrolland** [comment] 2018-12-03 08:57
Having a one-stop shop tool for a language is great and provides consistency. Part of stack's added value was this. 

The next best thing is to have one tool per functionality (initialize project, compile, publish, document..)

I guess that's the kind of tooling benefit @m-renaud is pointing at.
 
Not sure if it should be in summoner, but if so maybe a simple way to provide this would be to detect if stack is installed. If it is, then offer the possibility use template and delegate the task to stack via shelling out.

**Comment by vrom911** [comment] 2018-12-03 09:34
@nrolland I agree that it would be nice! 
The problem is that it would be much nicer to be able to create it not only via Stack, that's why we are discussing so many difficulties here 😞 

In the ideal world the templates should be more flexible, so you can use only certain parts of it if you want so.
I was even thinking on our own template system (but with the support of the Stack templates, of course, to keep the backwards compatibility with all the templates) but which could be much more configurable, at least in the way that Summoner is (for example, turn on/off tests, GitHub etc.). But this is just a crazy idea yet. We need to think about it more.

Let's see if we will get any news on the Stack template library, and then decide where to go further. I guess, your point about using Stack also makes sense, but let's see whether we could do better :)

**Comment by vrom911** [comment] 2020-02-22 14:50
Currently, `summoner` has the feature of the custom file creation. That means that with the custom `summoner.toml` you can add any files to your project at the moment of the generation. These files can be taken from the link online, locally or their input could be manually added in the config as well (see `files` option of the config).

> Custom mapping of files to their sources. Represented as a list of inline tables in TOML in a format like 
> ```toml
> files = 
>     [ { path = "foo"
>       , url = "https://..." 
>       }
>     , ... 
>     ]
> ``` 
> Supported file types: `url`, `local`, `raw`.


I think this is the maximum that summoner can add in here. Supporting templating is way out of the plans for this tool, so I am for closing this issue at the moment. Unfortunately, though the intention is very clear and helpful, it is not possible to add this at the moment.

**Closed by vrom911** 2020-02-22 14:50 UTC
Labels: question, wontfix
