### ISSUE TITLE
option for git without github?

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#301] opened 2019-04-05 08:45 UTC
Sometimes I don't want to create a new github project immediately...
Pushing a skeleton project immediately to github etc seems less useful.
Maybe an option just to setup a local git repo would be good?

I would prefer to do the initial github push as a separate step.

**Comment by vrom911** [comment] 2019-04-05 09:07
Duplicate of #300

**Closed by vrom911** 2019-04-05 09:07 UTC
