### ISSUE TITLE
Latest version of summoner is difficult to install

### ISSUE THREAD

**Issue by nlander** [kowainik/summoner#480] opened 2020-07-06 19:02 UTC
I have tried two methods of installing summoner, and both seem to have issues.
```
stack install summoner
```
does not install anything beyond version 1.2.0

I have also tried the apt installation (I am running Pop!_Os 20.04) and I get this error:
```
E: The repository 'http://ppa.launchpad.net/kowainik/summoner-cli/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
after I run
```
sudo add-apt-repository ppa:kowainik/summoner-cli
```

**Comment by chshersh** [comment] 2020-07-07 13:38
Because of how Stack and Stackage works, there is no guarantee that package will be in your global default resolver. In this case, it seems that your default global snapshot is very old and doesn't contain Summoner. If you want to install Summoner from Stackage, you need to specify explicitly the newer resolver that contains the desired version of Summoner, e.g.:

```
stack install summoner --resolver=lts-16.4
```

The README now contains information about whether the Summoner is in the latest Stackage resolver. But it's up to you to figure out the proper resolver to install the Summoner if you choose to install Summoner from Stackage because we are not in control of the default global Stack snapshot on your system.

> I have also tried the apt installation (I am running Pop!_Os 20.04) and I get this error:

Installation instructions explicitly tell about Ubuntu. I don't have access to Pop!_Os 20.04 and can't test installation in there. The instructions were tested on Ubuntu 18.04 on multiple machines, and they were confirmed to be working. I can also recommend to refer to the man page from your error message and see what you can do about this.

If there's a simple fix for this problem that won't break already working installation, you can contribute the patch to this repo:

* https://github.com/kowainik/ppa

**Closed by chshersh** 2020-07-07 13:38 UTC
Labels: question
